openapi: 3.0.3
info:
  title: "Plataforma de Seguridad Ciudadana API"
  description: "API para la gestión de reportes de incidentes y seguridad ciudadana."
  version: "1.0.0"

paths:
  /usuarios:
    post:
      summary: "Registro de usuario"
      description: "Permite registrar un nuevo usuario en la plataforma."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UsuarioRegistro"
      responses:
        "201":
          description: "Usuario registrado exitosamente."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UsuarioRespuesta"
        "400":
          description: "Datos de entrada no válidos."

  /usuarios/{id}:
    put:
      summary: "Actualizacion de datos"
      description: "Permite al usuario actualizar sus datos personales."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UsuarioActualizado"
      responses:
        "201":
          description: "Usuario registrado exitosamente."
        "400":
          description: "Datos de entrada no válidos."

    delete:
      summary: "Solicitud para eliminar la cuenta."
      description: "Solicituda para que la cuenta del usuario sea eliminada."
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "201":
          description: "Usuario eliminado exitosamente."
        "400":
          description: "Datos de entrada no válidos."
        "404":
          description: "Usuario no encontrado."

  /auth/login:
    post:
      summary: "Inicio de sesión"
      description: "Permite a un usuario autenticarse en la plataforma."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: "Inicio de sesión exitoso."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginRespuesta"
        "401":
          description: "Credenciales incorrectas."

  /auth/activar:
    post:
      summary: "Activar cuenta"
      description: "Permite activar la cuenta de un usuario con un código de verificación."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ActivarCuentaRequest"
      responses:
        "200":
          description: "Cuenta activada exitosamente."
        "400":
          description: "Código inválido o expirado."

  /auth/recuperar-password:
    post:
      summary: "Recuperar contraseña"
      description: "Envía un código de recuperación al correo del usuario."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RecuperarPasswordRequest"
      responses:
        "200":
          description: "Correo de recuperación enviado exitosamente."
        "404":
          description: "Usuario no encontrado."

  /auth/reset-password:
    post:
      summary: "Restablecer contraseña"
      description: "Permite cambiar la contraseña usando un código de recuperación."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ResetPasswordRequest"
      responses:
        "200":
          description: "Contraseña restablecida exitosamente."
        "400":
          description: "Código inválido o expirado."
components:
  schemas:


    UsuarioRegistro:
      type: "object"
      properties:
        nombre:
          type: "string"
          example: "Juan Pérez"
        correo:
          type: "string"
          format: "email"
          example: "juan.perez@email.com"
        ciudad:
          type: "string"
          example: "Armenia - Qundio"
        direccion:
          type: "string"
          example: "Cll 20 # 26-22 Brr San Jose"
        password:
          type: "string"
          format: "password"
        telefono:
          type: "string"
          example: "+573205113628"

    UsuarioRespuesta:
      type: "object"
      properties:
        nombre:
          type: "string"
        correo:
          type: "string"
        estado:
          type: "string"
          enum: ["pendiente", "activo"]


    UsuarioActualizado:
      type: "object"
      properties:
        NuevoNombre:
          type: string
        NuevaCiudad:
          type: string
        NuevoTelefono:
          type: string
        NuevaDireccion:
          type: string


    LoginRequest:
      type: "object"
      properties:
        correo:
          type: "string"
          format: "email"
        password:
          type: "string"
          format: "password"

    LoginRespuesta:
      type: "object"
      properties:
        token:
          type: "string"
          example: "eyJhbGciOiJIUzI1..."
        usuario:
          $ref: "#/components/schemas/UsuarioRespuesta"


    ActivarCuentaRequest:
      type: "object"
      properties:
        correo:
          type: "string"
        codigo:
          type: "string"
          example: "123456"


    RecuperarPasswordRequest:
      type: "object"
      properties:
        correo:
          type: "string"

    ResetPasswordRequest:
      type: "object"
      properties:
        correo:
          type: "string"
        codigo:
          type: "string"
        nuevaPassword:
          type: "string"
          format: "password"
